#include "PluginProcessor.h"
#include "PluginEditor.h"
DrumAliveAudioProcessor::DrumAliveAudioProcessor():AudioProcessor(BusesProperties().withOutput("Output",juce::AudioChannelSet::stereo(),true)),state(*this,nullptr,"PARAMS",createParams()){}
juce::AudioProcessorValueTreeState::ParameterLayout DrumAliveAudioProcessor::createParams(){juce::AudioProcessorValueTreeState::ParameterLayout p; auto add=[&](const char* id,const char* name,float a,float b,float d){p.add(std::make_unique<juce::AudioParameterFloat>(id,name,juce::NormalisableRange<float>(a,b),d));};add("variation","Variation",0,100,25);add("humanize","Humanize",0,100,15);add("tone","Tone",-100,100,0);add("decay","Decay",10,200,100);add("output","Output",-24,6,0);return p;}
void DrumAliveAudioProcessor::prepareToPlay(double sr,int){rate=sr;}
void DrumAliveAudioProcessor::releaseResources(){}
bool DrumAliveAudioProcessor::isBusesLayoutSupported(const BusesLayout& l)const{return l.getMainOutputChannelSet()==juce::AudioChannelSet::mono()||l.getMainOutputChannelSet()==juce::AudioChannelSet::stereo();}
void DrumAliveAudioProcessor::loadSample(const juce::File& f){juce::AudioFormatManager fm;fm.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader> r(fm.createReaderFor(f));if(!r)return;auto n=(int)juce::jmin<int64>(r->lengthInSamples,rate*20);juce::AudioBuffer<float> b((int)r->numChannels,n);r->read(&b,0,n,0,true,true);sample=std::move(b);sourceRate=r->sampleRate;sampleName=f.getFileName();}
void DrumAliveAudioProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer& midi){juce::ScopedNoDenormals no; b.clear();auto* v=state.getRawParameterValue("variation");auto* h=state.getRawParameterValue("humanize");auto* tone=state.getRawParameterValue("tone");auto* decay=state.getRawParameterValue("decay");auto* out=state.getRawParameterValue("output");for(const auto m:midi){auto msg=m.getMessage();if(msg.isNoteOn()&&sample.getNumSamples()>0){auto it=std::find_if(voices.begin(),voices.end(),[](auto& x){return !x.active;});if(it==voices.end())it=voices.begin();float vel=msg.getFloatVelocity();float var=v->load()/100.f;it->pos=0;it->vel=vel;it->gain=juce::jlimit(.5f,1.5f,1.f+(random.nextFloat()*2-1)*var*.22f);it->step=sourceRate/rate*std::pow(2.f,(random.nextFloat()*2-1)*var*.035f);it->filter=0;it->active=true;}}
 float gain=juce::Decibels::decibelsToGain(out->load());float toneMul=std::pow(2.f,tone->load()/120.f);for(int i=0;i<b.getNumSamples();++i){float x=0;for(auto& voice:voices)if(voice.active){int ix=(int)voice.pos;if(ix>=sample.getNumSamples()){voice.active=false;continue;}float s=0;for(int c=0;c<sample.getNumChannels();++c)s+=sample.getSample(c,ix);s/=juce::jmax(1,sample.getNumChannels());float env=std::pow(1.f-juce::jlimit(0.f,1.f,(float)(voice.pos/sample.getNumSamples())),100.f/juce::jmax(10.f,decay->load()));voice.filter+=juce::jlimit(.01f,.99f,.2f*toneMul)*(s-voice.filter);x+=voice.filter*voice.vel*voice.gain*env;voice.pos+=voice.step;}x*=gain;for(int c=0;c<b.getNumChannels();++c)b.setSample(c,i,x);}}
juce::AudioProcessorEditor* DrumAliveAudioProcessor::createEditor(){return new DrumAliveAudioProcessorEditor(*this);}void DrumAliveAudioProcessor::getStateInformation(juce::MemoryBlock& d){auto x=state.copyState();std::unique_ptr<juce::XmlElement> xml(x.createXml());copyXmlToBinary(*xml,d);}void DrumAliveAudioProcessor::setStateInformation(const void* d,int n){std::unique_ptr<juce::XmlElement>x(getXmlFromBinary(d,n));if(x&&x->hasTagName(state.state.getType()))state.replaceState(juce::ValueTree::fromXml(*x));}
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new DrumAliveAudioProcessor();}
